/*
Ledgera core API

Ledgera servers.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the HelperPaginatedArrayLedgerJournalEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelperPaginatedArrayLedgerJournalEntry{}

// HelperPaginatedArrayLedgerJournalEntry struct for HelperPaginatedArrayLedgerJournalEntry
type HelperPaginatedArrayLedgerJournalEntry struct {
	Data []LedgerJournalEntry `json:"data,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
}

// NewHelperPaginatedArrayLedgerJournalEntry instantiates a new HelperPaginatedArrayLedgerJournalEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelperPaginatedArrayLedgerJournalEntry() *HelperPaginatedArrayLedgerJournalEntry {
	this := HelperPaginatedArrayLedgerJournalEntry{}
	return &this
}

// NewHelperPaginatedArrayLedgerJournalEntryWithDefaults instantiates a new HelperPaginatedArrayLedgerJournalEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelperPaginatedArrayLedgerJournalEntryWithDefaults() *HelperPaginatedArrayLedgerJournalEntry {
	this := HelperPaginatedArrayLedgerJournalEntry{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *HelperPaginatedArrayLedgerJournalEntry) GetData() []LedgerJournalEntry {
	if o == nil || IsNil(o.Data) {
		var ret []LedgerJournalEntry
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelperPaginatedArrayLedgerJournalEntry) GetDataOk() ([]LedgerJournalEntry, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *HelperPaginatedArrayLedgerJournalEntry) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []LedgerJournalEntry and assigns it to the Data field.
func (o *HelperPaginatedArrayLedgerJournalEntry) SetData(v []LedgerJournalEntry) {
	o.Data = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *HelperPaginatedArrayLedgerJournalEntry) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelperPaginatedArrayLedgerJournalEntry) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *HelperPaginatedArrayLedgerJournalEntry) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *HelperPaginatedArrayLedgerJournalEntry) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

func (o HelperPaginatedArrayLedgerJournalEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelperPaginatedArrayLedgerJournalEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableHelperPaginatedArrayLedgerJournalEntry struct {
	value *HelperPaginatedArrayLedgerJournalEntry
	isSet bool
}

func (v NullableHelperPaginatedArrayLedgerJournalEntry) Get() *HelperPaginatedArrayLedgerJournalEntry {
	return v.value
}

func (v *NullableHelperPaginatedArrayLedgerJournalEntry) Set(val *HelperPaginatedArrayLedgerJournalEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableHelperPaginatedArrayLedgerJournalEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableHelperPaginatedArrayLedgerJournalEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelperPaginatedArrayLedgerJournalEntry(val *HelperPaginatedArrayLedgerJournalEntry) *NullableHelperPaginatedArrayLedgerJournalEntry {
	return &NullableHelperPaginatedArrayLedgerJournalEntry{value: val, isSet: true}
}

func (v NullableHelperPaginatedArrayLedgerJournalEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelperPaginatedArrayLedgerJournalEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


