/*
Ledgera API

teste

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the HttpQueryAccountPlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpQueryAccountPlan{}

// HttpQueryAccountPlan struct for HttpQueryAccountPlan
type HttpQueryAccountPlan struct {
	Id string `json:"id"`
}

// NewHttpQueryAccountPlan instantiates a new HttpQueryAccountPlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpQueryAccountPlan(id string) *HttpQueryAccountPlan {
	this := HttpQueryAccountPlan{}
	this.Id = id
	return &this
}

// NewHttpQueryAccountPlanWithDefaults instantiates a new HttpQueryAccountPlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpQueryAccountPlanWithDefaults() *HttpQueryAccountPlan {
	this := HttpQueryAccountPlan{}
	return &this
}

// GetId returns the Id field value
func (o *HttpQueryAccountPlan) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HttpQueryAccountPlan) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HttpQueryAccountPlan) SetId(v string) {
	o.Id = v
}

func (o HttpQueryAccountPlan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpQueryAccountPlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableHttpQueryAccountPlan struct {
	value *HttpQueryAccountPlan
	isSet bool
}

func (v NullableHttpQueryAccountPlan) Get() *HttpQueryAccountPlan {
	return v.value
}

func (v *NullableHttpQueryAccountPlan) Set(val *HttpQueryAccountPlan) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpQueryAccountPlan) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpQueryAccountPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpQueryAccountPlan(val *HttpQueryAccountPlan) *NullableHttpQueryAccountPlan {
	return &NullableHttpQueryAccountPlan{value: val, isSet: true}
}

func (v NullableHttpQueryAccountPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpQueryAccountPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


