/*
API ledgera

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UnprocessableEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnprocessableEntity{}

// UnprocessableEntity struct for UnprocessableEntity
type UnprocessableEntity struct {
	Message *string `json:"message,omitempty"`
	Errors []ValidationError `json:"errors,omitempty"`
}

// NewUnprocessableEntity instantiates a new UnprocessableEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnprocessableEntity() *UnprocessableEntity {
	this := UnprocessableEntity{}
	return &this
}

// NewUnprocessableEntityWithDefaults instantiates a new UnprocessableEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnprocessableEntityWithDefaults() *UnprocessableEntity {
	this := UnprocessableEntity{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UnprocessableEntity) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnprocessableEntity) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UnprocessableEntity) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UnprocessableEntity) SetMessage(v string) {
	o.Message = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *UnprocessableEntity) GetErrors() []ValidationError {
	if o == nil || IsNil(o.Errors) {
		var ret []ValidationError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnprocessableEntity) GetErrorsOk() ([]ValidationError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *UnprocessableEntity) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ValidationError and assigns it to the Errors field.
func (o *UnprocessableEntity) SetErrors(v []ValidationError) {
	o.Errors = v
}

func (o UnprocessableEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnprocessableEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableUnprocessableEntity struct {
	value *UnprocessableEntity
	isSet bool
}

func (v NullableUnprocessableEntity) Get() *UnprocessableEntity {
	return v.value
}

func (v *NullableUnprocessableEntity) Set(val *UnprocessableEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableUnprocessableEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableUnprocessableEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnprocessableEntity(val *UnprocessableEntity) *NullableUnprocessableEntity {
	return &NullableUnprocessableEntity{value: val, isSet: true}
}

func (v NullableUnprocessableEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnprocessableEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


