/*
Ledgera core API

Ledgera servers.

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the BillingCreateBulkBilling type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingCreateBulkBilling{}

// BillingCreateBulkBilling struct for BillingCreateBulkBilling
type BillingCreateBulkBilling struct {
	Data []BillingCreateBilling `json:"data"`
}

// NewBillingCreateBulkBilling instantiates a new BillingCreateBulkBilling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingCreateBulkBilling(data []BillingCreateBilling) *BillingCreateBulkBilling {
	this := BillingCreateBulkBilling{}
	this.Data = data
	return &this
}

// NewBillingCreateBulkBillingWithDefaults instantiates a new BillingCreateBulkBilling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingCreateBulkBillingWithDefaults() *BillingCreateBulkBilling {
	this := BillingCreateBulkBilling{}
	return &this
}

// GetData returns the Data field value
func (o *BillingCreateBulkBilling) GetData() []BillingCreateBilling {
	if o == nil {
		var ret []BillingCreateBilling
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BillingCreateBulkBilling) GetDataOk() ([]BillingCreateBilling, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BillingCreateBulkBilling) SetData(v []BillingCreateBilling) {
	o.Data = v
}

func (o BillingCreateBulkBilling) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingCreateBulkBilling) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableBillingCreateBulkBilling struct {
	value *BillingCreateBulkBilling
	isSet bool
}

func (v NullableBillingCreateBulkBilling) Get() *BillingCreateBulkBilling {
	return v.value
}

func (v *NullableBillingCreateBulkBilling) Set(val *BillingCreateBulkBilling) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingCreateBulkBilling) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingCreateBulkBilling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingCreateBulkBilling(val *BillingCreateBulkBilling) *NullableBillingCreateBulkBilling {
	return &NullableBillingCreateBulkBilling{value: val, isSet: true}
}

func (v NullableBillingCreateBulkBilling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingCreateBulkBilling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


