/*
ledgera

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ExceptionEntityNotFound type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExceptionEntityNotFound{}

// ExceptionEntityNotFound struct for ExceptionEntityNotFound
type ExceptionEntityNotFound struct {
	Entity *string `json:"entity,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewExceptionEntityNotFound instantiates a new ExceptionEntityNotFound object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExceptionEntityNotFound() *ExceptionEntityNotFound {
	this := ExceptionEntityNotFound{}
	return &this
}

// NewExceptionEntityNotFoundWithDefaults instantiates a new ExceptionEntityNotFound object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExceptionEntityNotFoundWithDefaults() *ExceptionEntityNotFound {
	this := ExceptionEntityNotFound{}
	return &this
}

// GetEntity returns the Entity field value if set, zero value otherwise.
func (o *ExceptionEntityNotFound) GetEntity() string {
	if o == nil || IsNil(o.Entity) {
		var ret string
		return ret
	}
	return *o.Entity
}

// GetEntityOk returns a tuple with the Entity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExceptionEntityNotFound) GetEntityOk() (*string, bool) {
	if o == nil || IsNil(o.Entity) {
		return nil, false
	}
	return o.Entity, true
}

// HasEntity returns a boolean if a field has been set.
func (o *ExceptionEntityNotFound) HasEntity() bool {
	if o != nil && !IsNil(o.Entity) {
		return true
	}

	return false
}

// SetEntity gets a reference to the given string and assigns it to the Entity field.
func (o *ExceptionEntityNotFound) SetEntity(v string) {
	o.Entity = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExceptionEntityNotFound) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExceptionEntityNotFound) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExceptionEntityNotFound) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExceptionEntityNotFound) SetId(v string) {
	o.Id = &v
}

func (o ExceptionEntityNotFound) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExceptionEntityNotFound) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Entity) {
		toSerialize["entity"] = o.Entity
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableExceptionEntityNotFound struct {
	value *ExceptionEntityNotFound
	isSet bool
}

func (v NullableExceptionEntityNotFound) Get() *ExceptionEntityNotFound {
	return v.value
}

func (v *NullableExceptionEntityNotFound) Set(val *ExceptionEntityNotFound) {
	v.value = val
	v.isSet = true
}

func (v NullableExceptionEntityNotFound) IsSet() bool {
	return v.isSet
}

func (v *NullableExceptionEntityNotFound) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExceptionEntityNotFound(val *ExceptionEntityNotFound) *NullableExceptionEntityNotFound {
	return &NullableExceptionEntityNotFound{value: val, isSet: true}
}

func (v NullableExceptionEntityNotFound) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExceptionEntityNotFound) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


